In [33]:
import pandas as pd

In [34]:
df_train = pd.read_csv("preprocessed/train_with_bb_features.csv")
df_test = pd.read_csv("preprocessed/test_with_bb_features.csv")

In [35]:
df_train.head()

,user_id,browser,os,country_id,region_id,timezone_id,domain,event_count,component0,component1,...,bb_23,bb_24,bb_25,bb_26,bb_27,bb_28,bb_29,bb_30,bb_31,target
0,00006a10d9ff5f9d312029ac4d296430,YandexSearch,Android,c31b4e,470e75,f6155e,6a81948,1,10214.0,-1254.0,...,0.141555,0.519237,0.126132,0.0,0.034210,0.024856,0.135293,0.492822,0.171879,1.0
1,00008d5fd6bff19884138510b077a22b,Yandex Browser,iOS,c31b4e,1fbfa5,e56e80,6a81948,1,10214.0,-1254.0,...,0.116888,0.440709,0.015529,0.0,0.000000,0.048866,0.190242,0.542757,0.099703,1.0
2,000098f8aa8b68a125148caff0a02827,Chrome,Windows,e48e27,NaN,f0c3df,b53adc6,1,15633.0,22503.0,...,0.223871,0.366513,0.000000,0.0,0.000000,0.000000,0.000000,0.377329,0.000000,0.0
3,0000b0ec7cb23e402cc5bb0487deef4c,Chrome,Android,c31b4e,97023a,e56e80,b56ea20,2,12055.5,10011.5,...,0.376081,0.102755,0.217579,0.0,0.126420,0.000000,0.000000,0.298370,0.000000,1.0
4,0000be6a07f2fcfd68b8486d309e3a22,Chrome Mobile WebView,Android,c31b4e,380ef0,e56e80,9f1218f,1,-3578.0,2164.0,...,0.476787,0.176838,0.144666,0.0,0.109932,0.082522,0.189492,0.323432,0.000000,1.0

In [36]:
categorical_columns = [
    "browser",
    "os",
    "country_id",
    "region_id",
    "timezone_id",
    "domain",
    "event_count",
]
component_columns = [f"component{i}" for i in range(10)] + [
    f"bb_{i}" for i in range(32)
]

df_train[categorical_columns] = df_train[categorical_columns].fillna("NaN").astype(str)
df_test[categorical_columns] = df_test[categorical_columns].fillna("NaN").astype(str)

df_train_x = df_train[categorical_columns + component_columns].copy()
df_train_y = df_train["target"].astype("float32").values

df_test_x = df_test[categorical_columns + component_columns].copy()
df_test_ids = df_test["user_id"].copy()

In [37]:
df_train_x.head()

,browser,os,country_id,region_id,timezone_id,domain,event_count,component0,component1,component2,...,bb_22,bb_23,bb_24,bb_25,bb_26,bb_27,bb_28,bb_29,bb_30,bb_31
0,YandexSearch,Android,c31b4e,470e75,f6155e,6a81948,1,10214.0,-1254.0,10495.0,...,0.329580,0.141555,0.519237,0.126132,0.0,0.034210,0.024856,0.135293,0.492822,0.171879
1,Yandex Browser,iOS,c31b4e,1fbfa5,e56e80,6a81948,1,10214.0,-1254.0,10495.0,...,0.333555,0.116888,0.440709,0.015529,0.0,0.000000,0.048866,0.190242,0.542757,0.099703
2,Chrome,Windows,e48e27,NaN,f0c3df,b53adc6,1,15633.0,22503.0,-2155.0,...,0.395369,0.223871,0.366513,0.000000,0.0,0.000000,0.000000,0.000000,0.377329,0.000000
3,Chrome,Android,c31b4e,97023a,e56e80,b56ea20,2,12055.5,10011.5,10496.0,...,0.285280,0.376081,0.102755,0.217579,0.0,0.126420,0.000000,0.000000,0.298370,0.000000
4,Chrome Mobile WebView,Android,c31b4e,380ef0,e56e80,9f1218f,1,-3578.0,2164.0,-12993.0,...,0.182995,0.476787,0.176838,0.144666,0.0,0.109932,0.082522,0.189492,0.323432,0.000000

In [38]:
df_test_x.head()

,browser,os,country_id,region_id,timezone_id,domain,event_count,component0,component1,component2,...,bb_22,bb_23,bb_24,bb_25,bb_26,bb_27,bb_28,bb_29,bb_30,bb_31
0,Chrome,Windows,e48e27,NaN,f0c3df,b53adc6,1,15633.0,22503.0,-2155.0,...,0.395369,0.223871,0.366513,0.000000,0.0,0.000000,0.000000,0.000000,0.377329,0.000000
1,Chrome,Android,c31b4e,37246e,b4a275,72879b4,1,1489.0,15548.0,1283.0,...,0.185387,0.198332,0.268159,0.000000,0.0,0.000000,0.000000,0.124253,0.235184,0.000000
2,Chrome,Windows,9bd92f,NaN,100cd5d,b6630fd,1,18530.0,14117.0,9243.0,...,0.353522,0.099013,0.284027,0.118770,0.0,0.000000,0.000000,0.047473,0.223296,0.000000
3,Chrome Mobile,Android,c31b4e,380ef0,e56e80,635e50c,1,15290.0,-740.0,12145.0,...,0.280179,0.576092,0.221572,0.324951,0.0,0.143671,0.223182,0.236112,0.259828,0.000000
4,Chrome Mobile,Android,c31b4e,f66ff,f6155e,7f91a1d,1,19051.0,9021.0,9045.0,...,0.237485,0.373404,0.003393,0.248822,0.0,0.175628,0.292717,0.140843,0.208554,0.085369

In [39]:
from sklearn.model_selection import train_test_split

df_train_x, df_val_x, df_train_y, df_val_y = train_test_split(
    df_train_x, df_train_y, test_size=0.1, random_state=42, stratify=df_train_y
)

df_train_x = df_train_x.reset_index(drop=True)
df_val_x = df_val_x.reset_index(drop=True)

In [40]:
from category_encoders import CatBoostEncoder

cbe = CatBoostEncoder(cols=categorical_columns, random_state=42)

cbe.fit(df_train_x, df_train_y)

df_train_x_te = cbe.transform(df_train_x)
df_val_x_te = cbe.transform(df_val_x)
df_test_x_te = cbe.transform(df_test_x)

In [41]:
df_train_x_te.head()

,browser,os,country_id,region_id,timezone_id,domain,event_count,component0,component1,component2,...,bb_22,bb_23,bb_24,bb_25,bb_26,bb_27,bb_28,bb_29,bb_30,bb_31
0,0.210656,0.474222,0.460195,0.444045,0.443963,0.188171,0.475435,-3578.0,2164.0,-12993.0,...,0.200490,0.463113,0.220809,0.124110,0.0,0.076000,0.132941,0.160342,0.310219,0.000000
1,0.486622,0.474222,0.460195,0.475790,0.466548,0.889030,0.482620,11300.0,13201.0,-4193.0,...,0.182682,0.344691,0.264288,0.000000,0.0,0.081858,0.007781,0.011721,0.287215,0.143316
2,0.135176,0.474222,0.469913,0.347696,0.469913,0.155396,0.475435,20773.0,11527.0,10472.0,...,0.293031,0.434772,0.036630,0.329295,0.0,0.289872,0.259256,0.140200,0.396922,0.000000
3,0.486622,0.474222,0.460195,0.475790,0.466548,0.452169,0.475435,6834.0,13447.0,665.0,...,0.241437,0.209987,0.383886,0.042883,0.0,0.000000,0.115488,0.131629,0.381408,0.000000
4,0.486622,0.474222,0.460195,0.475790,0.466548,0.452169,0.475435,5620.0,8307.0,8806.0,...,0.246759,0.168938,0.409547,0.034674,0.0,0.000000,0.069439,0.126883,0.340918,0.000000

In [42]:
from random import randint
from catboost import CatBoostClassifier


def train_catboost(x_train, y_train, x_val, y_val, seed):
    model = CatBoostClassifier(
        loss_function="Logloss",
        eval_metric="AUC",
        task_type="GPU",
        depth=10,
        l2_leaf_reg=10,
        min_data_in_leaf=100,
        learning_rate=0.01,
        iterations=1000,
        early_stopping_rounds=100,
        random_seed=seed,
        verbose=False,
    )
    model.fit(
        x_train,
        y_train,
        eval_set=(x_val, y_val),
        cat_features=categorical_columns,
        verbose=100,
    )
    return model

In [43]:
from tqdm import tqdm

seeds = [randint(1, 10000) for i in range(3)]
models = []

for s in tqdm(seeds):
    print(f"Training model seed={s}")
    m = train_catboost(df_train_x, df_train_y, df_val_x, df_val_y, seed=s)
    models.append(m)

  0%|          | 0/3 [00:00<?, ?it/s]

Training model seed=1033

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9002524	best: 0.9002524 (0)	total: 134ms	remaining: 2m 13s
100:	test: 0.9107537	best: 0.9107537 (100)	total: 13.6s	remaining: 2m 1s
200:	test: 0.9130676	best: 0.9130676 (200)	total: 30.4s	remaining: 2m
300:	test: 0.9149147	best: 0.9149147 (300)	total: 53.7s	remaining: 2m 4s
400:	test: 0.9163111	best: 0.9163111 (400)	total: 1m 7s	remaining: 1m 40s
500:	test: 0.9173533	best: 0.9173533 (500)	total: 1m 20s	remaining: 1m 20s
600:	test: 0.9182520	best: 0.9182520 (600)	total: 1m 33s	remaining: 1m 2s
700:	test: 0.9190153	best: 0.9190153 (700)	total: 1m 47s	remaining: 45.8s
800:	test: 0.9197530	best: 0.9197530 (800)	total: 2m	remaining: 30.1s
900:	test: 0.9203448	best: 0.9203448 (900)	total: 2m 14s	remaining: 14.8s
999:	test: 0.9209334	best: 0.9209334 (999)	total: 2m 27s	remaining: 0us
bestTest = 0.9209334254
bestIteration = 999

 33%|███▎      | 1/3 [02:32<05:04, 152.37s/it]

Training model seed=6766

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9003047	best: 0.9003047 (0)	total: 184ms	remaining: 3m 3s
100:	test: 0.9107253	best: 0.9107253 (100)	total: 13.9s	remaining: 2m 3s
200:	test: 0.9131308	best: 0.9131308 (200)	total: 27.3s	remaining: 1m 48s
300:	test: 0.9149604	best: 0.9149604 (300)	total: 46.9s	remaining: 1m 48s
400:	test: 0.9163122	best: 0.9163122 (400)	total: 1m 7s	remaining: 1m 40s
500:	test: 0.9173782	best: 0.9173782 (500)	total: 1m 21s	remaining: 1m 21s
600:	test: 0.9182276	best: 0.9182276 (600)	total: 1m 35s	remaining: 1m 3s
700:	test: 0.9189958	best: 0.9189958 (700)	total: 1m 48s	remaining: 46.4s
800:	test: 0.9196695	best: 0.9196695 (800)	total: 2m 2s	remaining: 30.4s
900:	test: 0.9202320	best: 0.9202320 (900)	total: 2m 15s	remaining: 14.9s
999:	test: 0.9207906	best: 0.9207906 (999)	total: 2m 31s	remaining: 0us
bestTest = 0.9207905829
bestIteration = 999

 67%|██████▋   | 2/3 [05:08<02:34, 154.37s/it]

Training model seed=1011

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.8979344	best: 0.8979344 (0)	total: 232ms	remaining: 3m 51s
100:	test: 0.9107036	best: 0.9107036 (100)	total: 14s	remaining: 2m 4s
200:	test: 0.9130528	best: 0.9130528 (200)	total: 28s	remaining: 1m 51s
300:	test: 0.9148858	best: 0.9148858 (300)	total: 41.4s	remaining: 1m 36s
400:	test: 0.9162711	best: 0.9162711 (400)	total: 57.6s	remaining: 1m 26s
500:	test: 0.9172994	best: 0.9172994 (500)	total: 1m 11s	remaining: 1m 10s
600:	test: 0.9182069	best: 0.9182069 (600)	total: 1m 25s	remaining: 56.6s
700:	test: 0.9189404	best: 0.9189404 (700)	total: 1m 39s	remaining: 42.3s
800:	test: 0.9196486	best: 0.9196486 (800)	total: 1m 52s	remaining: 28.1s
900:	test: 0.9202831	best: 0.9202831 (900)	total: 2m 7s	remaining: 14s
999:	test: 0.9208500	best: 0.9208500 (999)	total: 2m 22s	remaining: 0us
bestTest = 0.9208499789
bestIteration = 999

100%|██████████| 3/3 [07:35<00:00, 151.86s/it]

In [44]:
import numpy as np

val_probs = np.zeros(len(df_val_y))

for m in models:
    val_probs += m.predict_proba(df_val_x)[:, 1]

val_probs /= len(models)

In [45]:
import numpy as np
from sklearn.metrics import accuracy_score


def find_best_threshold(probs, y_true):
    thresholds = np.linspace(0.01, 0.99, 200)
    best_threshold = 0
    best_accuracy = 0

    for thr in thresholds:
        preds = (probs >= thr).astype(int)
        acc = accuracy_score(y_true, preds)
        if acc > best_accuracy:
            best_accuracy = acc
            best_threshold = thr

    return best_threshold, best_accuracy

In [49]:
best_thr, best_acc = find_best_threshold(val_probs, df_val_y)
print("Best threshold: ", best_thr)
print("Best accuracy: ", best_acc)

Best threshold:  0.54678391959799
Best accuracy:  0.8581

In [50]:
test_probs = np.zeros(len(df_test_ids))

for m in models:
    test_probs += m.predict_proba(df_test_x)[:, 1]

test_probs /= len(models)

In [53]:
for i, m in enumerate(models):
    m.save_model(f"models/best_model{i}.cbm")

In [51]:
pd.DataFrame(
    {"user_id;target": df_test_ids.astype(str) + ";" + test_probs.astype(str)}
).to_csv("predictions/catboost_prediction.csv", index=False)